import { Plus_Jakarta_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/ui/themeProvider";
import "./globals.css";
import ClientToaster from "@/lib/ClientToaster";
import ModeToggle from "@/components/themeButton";
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus_jakarta_sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning className={jakarta.className}>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="absolute top-6 z-50 right-6">
              <ModeToggle />
            </div>
            {children}
            <ClientToaster richColors position="top-right" />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
